FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y \
    bash default-mysql-server kamailio kamailio-mysql-modules sngrep

RUN echo "DBENGINE=MYSQL" >> /etc/kamailio/kamctlrc

COPY kamailio /etc/default/kamailio
COPY kamailio.cfg /etc/kamailio/kamailio.cfg


COPY kamailio.sh /usr/local/bin
RUN  chmod +x /usr/local/bin/kamailio.sh


WORKDIR /home/ubuntu

ENTRYPOINT [ "kamailio.sh" ]