FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y \
    bash
RUN apt install nano -y
RUN apt install default-mysql-server -y
RUN apt install kamailio -y
RUN apt install kamailio-mysql-modules -y


RUN echo "DBENGINE=MYSQL" >> /etc/kamailio/kamctlrc

RUN service mysql start

COPY kamailio /etc/default/kamailio
COPY kamailio.cfg /etc/kamailio/kamailio.cfg


WORKDIR /home/ubuntu
