services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile_UA
    environment:
      PORT: "5061"
      CLIENT: "client1"
    container_name: client1
    tty: true
    networks:
      - my_network
    ports:
      - "5061:5061"
    cap_add:
    - NET_ADMIN

  client2:
    build:
      context: .
      dockerfile: Dockerfile_UA
    environment:
      PORT: "5062"
      CLIENT: "client2"
    container_name: client2
    tty: true
    networks:
      - my_network
    ports:
      - "5062:5062"
    cap_add:
    - NET_ADMIN

  b2bua:
    build:
      context: .
      dockerfile: Dockerfile_B2B
    container_name: b2bua
    tty: true
    stdin_open: true
    networks:
      - my_network
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
    cap_add:
    - NET_ADMIN

networks:
  my_network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1