services:
  client1:
    build:
      context: .
      dockerfile: UA.Dockerfile
    environment:
      PORT: "5091"
      CLIENT: "client1"
    container_name: client1
    tty: true
    networks:
      system-test:
        ipv4_address: 10.22.80.5
    ports:
      - "5091:5091"
    cap_add:
    - NET_ADMIN

  client2:
    build:
      context: .
      dockerfile: UA.Dockerfile
    environment:
      PORT: "5060"
      CLIENT: "client2"
    container_name: client2
    tty: true
    networks:
      system-test:
        ipv4_address: 10.22.80.6
    ports:
      - "5060:5060"
    cap_add:
    - NET_ADMIN

  freeswitch:
    build:
      context: .
      dockerfile: FreeSwitch.Dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    volumes:
      - /home/zaleos/Workspaces/sip-test-configuration/freeswitch/coredumps:/var/crash
      -  ./scripts:/etc/freeswitch/scripts
      -  ./config:/etc/freeswitch
      # - ./odbc.ini:/etc/odbc.ini
      # - ./odbcinst.ini:/etc/odbcinst.ini
    ulimits:
      core: -1
    environment:
      - IP_INIVR=10.22.80.2
      - IP_FREESWITCH=10.22.80.3
    networks:
      system-test:
        ipv4_address: 10.22.80.3

  db:
    build:
      context: .
      dockerfile: Database.Dockerfile
    environment:
      - POSTGRESQL_PASSWORD=1234
    # healthcheck:
    #   test: ["CMD", "mysql", "-h", "10.5.0.3", "-u", "root", "-pmysecretpassword", "-e", "SELECT 1"]
    #   interval: 1s
    #   timeout: 1s
    #   retries: 60
    #   start_period: 30s
    volumes:
      - ./create_free.sql:/create_free.sql
      - ./feed.sql:/feed.sql
    ulimits:
      core: -1
    networks:
      system-test:
        ipv4_address: 10.22.80.4

networks:
  system-test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.22.80.0/24
          gateway: 10.22.80.1
